### ISSUE TITLE
`eslint@8.x.x` has breaking changes 

### ISSUE THREAD

**Issue by jknight12882** [iamturns/eslint-config-airbnb-typescript#251]
```
    TypeError: Failed to load plugin '@typescript-eslint' declared in '.eslintrc.js » eslint-config-airbnb-typescript » /Users/:redacted/Workspace/:redacted/node_modules/eslint-config-airbnb-typescript/lib/shared.js': Class extends value undefined is not a constructor or null
        at Object.<anonymous> (/Users/:redacted/Workspace/:redacted/node_modules/@typescript-eslint/experimental-utils/dist/ts-eslint/CLIEngine.js:12:34)
        at Module._compile (/Users/:redacted/Workspace/:redacted/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
        at Module.load (node:internal/modules/cjs/loader:989:32)
        at Function.Module._load (node:internal/modules/cjs/loader:829:14)
        at Module.require (node:internal/modules/cjs/loader:1013:19)
        at require (/Users/:redacted/Workspace/:redacted/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
        at Object.<anonymous> (/Users/:redacted/Workspace/:redacted/node_modules/@typescript-eslint/experimental-utils/dist/ts-eslint/index.js:14:14)
        at Module._compile (/Users/:redacted/Workspace/:redacted/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
        at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
```

**Comment by Zamiell** [comment]
@iamturns Please also update the deps for `typescript-eslint/eslint-plugin` and ` @typescript-eslint/parser`.

**Comment by andrei9669** [comment]
my guess is that we first have to wait for this to be resolved?
https://github.com/airbnb/javascript/issues/2478

**Comment by iamturns** [comment]
Peer deps (`@typescript-eslint`) have been updated to the latest (5.0.0), which will help towards ESLint 8 support.

But as @andrei9669 has pointed out, we need to wait for `eslint-config-airbnb-base` to support ESLint 8 too, as it's a dependency of this library.

**Comment by ModyQyW** [comment]
`eslint-config-airbnb@19` and `eslint-config-airbnb-base@15` support ESLint 8 now. See https://github.com/airbnb/javascript/issues/2478.

**Comment by BohdanYavorskyi** [comment]
Can anybody (🥇) upgrade the `eslint-config-airbnb-base` in dependecies to 15th version to allow this package to support Eslint 8+?
