### ISSUE TITLE
"Error while loading rule '@typescript-eslint/no-implied-eval'" while migrating from 6.3.1 to 7.0.0

### ISSUE THREAD

**Issue by skasyn** [iamturns/eslint-config-airbnb-typescript#69]
While working on a react-typescript application, I tried to setup eslint the same way I used to one month ago.

I ran the following command :
```
npm install eslint-config-airbnb-typescript \
            eslint-plugin-import \
            eslint-plugin-jsx-a11y \
            eslint-plugin-react \
            eslint-plugin-react-hooks \
            @typescript-eslint/eslint-plugin \
            --save-dev
```

With this eslint configuration : 
```
parserOptions:
  ecmaVersion: 6

env:
  browser: true

extends:
  - airbnb-typescript
  - airbnb/hooks
  - plugin:@typescript-eslint/recommended

rules:
  react/react-in-jsx-scope: off
```

I ran `npm run lint` and I got an error :

# What I expected 

Eslint working as usual.

# What I got

```
Error: Error while loading rule '@typescript-eslint/no-implied-eval': You have used a rule which requires parserServices to be generated. You must therefore provide a value for the "parserOptions.project" property for @typescript-eslint/parser.
Occurred while linting /Users/skaas/project/src/App.test.tsx
    at Object.getParserServices (/Users/skaas/project/node_modules/@typescript-eslint/eslint-plugin/node_modules/@typescript-eslint/experimental-utils/dist/eslint-utils/getParserServices.js:15:15)
    at create (/Users/skaas/project/node_modules/@typescript-eslint/eslint-plugin/dist/rules/no-implied-eval.js:38:37)
    at Object.create (/Users/skaas/project/node_modules/@typescript-eslint/eslint-plugin/node_modules/@typescript-eslint/experimental-utils/dist/eslint-utils/RuleCreator.js:12:24)
    at createRuleListeners (/Users/skaas/project/node_modules/eslint/lib/linter/linter.js:746:21)
    at /Users/skaas/project/node_modules/eslint/lib/linter/linter.js:916:31
    at Array.forEach (<anonymous>)
    at runRules (/Users/skaas/project/node_modules/eslint/lib/linter/linter.js:861:34)
    at Linter._verifyWithoutProcessors (/Users/skaas/project/node_modules/eslint/lib/linter/linter.js:1157:31)
    at Linter._verifyWithConfigArray (/Users/skaas/project/node_modules/eslint/lib/linter/linter.js:1255:21)
    at Linter.verify (/Users/skaas/project/node_modules/eslint/lib/linter/linter.js:1210:25)
```

# How did I fix it 

I switched back to `"eslint-config-airbnb-typescript": "^6.3.1"` and it fixed the error.

**Comment by Geospace** [comment]
Looks like https://github.com/iamturns/eslint-config-airbnb-typescript/pull/63 is what you are looking for.

**Comment by skasyn** [comment]
Oh my bad, thanks for the link !
