### ISSUE TITLE
Error: `sourceCode.isSpaceBetween is not a function Occurred while linting`

### ISSUE THREAD

**Issue by basdnguyen** [iamturns/eslint-config-airbnb-typescript#70]
ESLint config:
`{
    "extends": ["airbnb-typescript"],
    "parserOptions": {
        "project": "./tsconfig.json",
    },
    "rules": {
        "semi": "error"
    }
}`

package.json:
`{
  "name": "prettier-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^2.19.2",
    "@typescript-eslint/parser": "^2.19.2",
    "eslint": "^6.1.0",
    "eslint-config-airbnb": "^18.0.1",
    "eslint-config-airbnb-typescript": "^7.0.0",
    "eslint-plugin-import": "^2.20.1",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-react": "^7.18.3",
    "eslint-plugin-react-hooks": "^1.7.0",
    "typescript": "^3.7.5"
  }
}
`

**Comment by psamim** [comment]
I have the same problem.

**Comment by iamturns** [comment]
Hey @basdnguyen and @psamim 

I think using the  equivalent `@typescript-eslint` rule will fix this problem.

Replace:

```
"semi": "error"
```

With:

```
"@typescript-eslint/semi": "error"
```

**Comment by basdnguyen** [comment]
@iamturns I tried your suggestion but without any luck

**Comment by iamturns** [comment]
Is it happening with everything you lint? Or does linting a particular
piece of code trigger this?

**Comment by basdnguyen** [comment]
`export default function() {
  var i = 0;
  const str = "abc";
  let a = '1';
  const obj={
    a: 1,
  }
}`

**Comment by iamturns** [comment]
Works fine for me.

`package.json`:

```
"devDependencies": {
    "@typescript-eslint/eslint-plugin": "^2.21.0",
    "eslint": "^6.8.0",
    "eslint-config-airbnb-typescript": "^7.0.0",
    "eslint-plugin-import": "^2.20.1",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-react": "^7.18.3",
    "eslint-plugin-react-hooks": "^2.4.0",
    "typescript": "^3.8.2"
  }
```

`.eslintrc.js`:

```
module.exports = {
  extends: ["airbnb-typescript"],
  parserOptions: {
    project: "./tsconfig.json"
  },
};
```

`tsconfig.json`

```
{
  "compilerOptions": {
    /* Basic Options */
    "target": "es5",                          /* Specify ECMAScript target version: 'ES3' (default), 'ES5', 'ES2015', 'ES2016', 'ES2017','ES2018' or 'ESNEXT'. */
    "module": "commonjs",                     /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', or 'ESNext'. */
    // "lib": [],                             /* Specify library files to be included in the compilation. */
    // "allowJs": true,                       /* Allow javascript files to be compiled. */
    // "checkJs": true,                       /* Report errors in .js files. */
    // "jsx": "preserve",                     /* Specify JSX code generation: 'preserve', 'react-native', or 'react'. */
    // "declaration": true,                   /* Generates corresponding '.d.ts' file. */
    // "declarationMap": true,                /* Generates a sourcemap for each corresponding '.d.ts' file. */
    // "sourceMap": true,                     /* Generates corresponding '.map' file. */
    // "outFile": "./",                       /* Concatenate and emit output to single file. */
    // "outDir": "./",                        /* Redirect output structure to the directory. */
    // "rootDir": "./",                       /* Specify the root directory of input files. Use to control the output directory structure with --outDir. */
    // "composite": true,                     /* Enable project compilation */
    // "removeComments": true,                /* Do not emit comments to output. */
    // "noEmit": true,                        /* Do not emit outputs. */
    // "importHelpers": true,                 /* Import emit helpers from 'tslib'. */
    // "downlevelIteration": true,            /* Provide full support for iterables in 'for-of', spread, and destructuring when targeting 'ES5' or 'ES3'. */
    // "isolatedModules": true,               /* Transpile each file as a separate module (similar to 'ts.transpileModule'). */

    /* Strict Type-Checking Options */
    "strict": true,                           /* Enable all strict type-checking options. */
    // "noImplicitAny": true,                 /* Raise error on expressions and declarations with an implied 'any' type. */
    // "strictNullChecks": true,              /* Enable strict null checks. */
    // "strictFunctionTypes": true,           /* Enable strict checking of function types. */
    // "strictPropertyInitialization": true,  /* Enable strict checking of property initialization in classes. */
    // "noImplicitThis": true,                /* Raise error on 'this' expressions with an implied 'any' type. */
    // "alwaysStrict": true,                  /* Parse in strict mode and emit "use strict" for each source file. */

    /* Additional Checks */
    // "noUnusedLocals": true,                /* Report errors on unused locals. */
    // "noUnusedParameters": true,            /* Report errors on unused parameters. */
    // "noImplicitReturns": true,             /* Report error when not all code paths in function return a value. */
    // "noFallthroughCasesInSwitch": true,    /* Report errors for fallthrough cases in switch statement. */

    /* Module Resolution Options */
    // "moduleResolution": "node",            /* Specify module resolution strategy: 'node' (Node.js) or 'classic' (TypeScript pre-1.6). */
    // "baseUrl": "./",                       /* Base directory to resolve non-absolute module names. */
    // "paths": {},                           /* A series of entries which re-map imports to lookup locations relative to the 'baseUrl'. */
    // "rootDirs": [],                        /* List of root folders whose combined content represents the structure of the project at runtime. */
    // "typeRoots": [],                       /* List of folders to include type definitions from. */
    // "types": [],                           /* Type declaration files to be included in compilation. */
    // "allowSyntheticDefaultImports": true,  /* Allow default imports from modules with no default export. This does not affect code emit, just typechecking. */
    "esModuleInterop": true                   /* Enables emit interoperability between CommonJS and ES Modules via creation of namespace objects for all imports. Implies 'allowSyntheticDefaultImports'. */
    // "preserveSymlinks": true,              /* Do not resolve the real path of symlinks. */

    /* Source Map Options */
    // "sourceRoot": "",                      /* Specify the location where debugger should locate TypeScript files instead of source locations. */
    // "mapRoot": "",                         /* Specify the location where debugger should locate map files instead of generated locations. */
    // "inlineSourceMap": true,               /* Emit a single file with source maps instead of having a separate file. */
    // "inlineSources": true,                 /* Emit the source alongside the sourcemaps within a single file; requires '--inlineSourceMap' or '--sourceMap' to be set. */

    /* Experimental Options */
    // "experimentalDecorators": true,        /* Enables experimental support for ES7 decorators. */
    // "emitDecoratorMetadata": true,         /* Enables experimental support for emitting type metadata for decorators. */
  }
}
```

`test.ts`:

```
export default function () {
  const i = 0;
  const str = 'abc';
  const a = '1';
  const obj = { a: 1 };
}
```

Result:

```
  2:9  error  'i' is assigned a value but never used    @typescript-eslint/no-unused-vars
  3:9  error  'str' is assigned a value but never used  @typescript-eslint/no-unused-vars
  4:9  error  'a' is assigned a value but never used    @typescript-eslint/no-unused-vars
  5:9  error  'obj' is assigned a value but never used  @typescript-eslint/no-unused-vars
```

This is the expected result.

Let me know where your setup or versions are different from above, so I can try to reproduce the error.

**Comment by mlukianenko** [comment]
The same issue.
<img width="486" alt="Screenshot 2020-02-26 at 13 27 37" src="https://user-images.githubusercontent.com/42577512/75340784-cf574680-589b-11ea-9120-fd2520ffcabd.png">

**Comment by iamturns** [comment]
I can't reproduce this issue, as shown above.
Can someone please provide additional information?

**Comment by basdnguyen** [comment]
Hi Matt, let me try with your config then I'll get back soon

**Comment by yupeilin123** [comment]
I have the same question too

**Comment by rdsedmundo** [comment]
I had eslint@6.1.0 and the same problem, upgraded to eslint@6.8.0 and it went way.

**Comment by colinmcparland** [comment]
Happening for me too, upgrading to eslint@6.8.0 didnt fix :(

eslintrc:
```
module.exports = {
  extends: ["airbnb-typescript"],
  parserOptions: {
    project: './tsconfig.json'
  },
  rules: {
    "react/prop-types": 0,
    "@typescript-eslint/quotes": [
      "error",
      "double",
      {
        avoidEscape: true
      }
    ]
  },
  settings: {
    react: {
      version: "detect",
    }
  },
};
```
Error output
```
TypeError: sourceCode.isSpaceBetween is not a function
Occurred while linting somepath/src/charts/single-line/single-line.tsx:1
    at validateCommaSpacing (somepath/node_modules/@typescript-eslint/eslint-plugin/dist/rules/comma-spacing.js:87:44)
    at Program:exit.tokensAndComments.forEach (somepath/node_modules/@typescript-eslint/eslint-plugin/dist/rules/comma-spacing.js:131:21)
    at Array.forEach (<anonymous>)
    at Program:exit (somepath/node_modules/@typescript-eslint/eslint-plugin/dist/rules/comma-spacing.js:125:35)
    at listeners.(anonymous function).forEach.listener (/Users/Colini/.nvm/versions/node/v10.14.2/lib/node_modules/eslint/lib/linter/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/Colini/.nvm/versions/node/v10.14.2/lib/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/Colini/.nvm/versions/node/v10.14.2/lib/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (/Users/Colini/.nvm/versions/node/v10.14.2/lib/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.leaveNode (/Users/Colini/.nvm/versions/node/v10.14.2/lib/node_modules/eslint/lib/linter/node-event-generator.js:306:14)
```
package.json
```
...
"devDependencies": {
    "@commitlint/cli": "^7.2.1",
    "@commitlint/config-conventional": "^8.3.4",
    "@storybook/addon-a11y": "^5.0.0",
    "@storybook/addon-actions": "^5.0.0",
    "@storybook/addon-links": "^5.0.0",
    "@storybook/addon-notes": "^5.0.0",
    "@storybook/addon-options": "^5.0.0",
    "@storybook/addons": "^5.0.0",
    "@storybook/cli": "^5.0.0",
    "@storybook/react": "^5.0.0",
    "@testing-library/jest-dom": "^4.0.0",
    "@testing-library/react": "^8.0.6",
    "@types/jest": "^24.0.9",
    "@types/node": "^11.10.4",
    "@types/ramda": "^0.25.42",
    "@types/react": "^16.7.13",
    "@types/react-dom": "^16.0.11",
    "@types/react-helmet": "^5.0.7",
    "@types/react-intl": "^2.3.14",
    "@types/react-redux": "^7.0.1",
    "@types/react-router-dom": "^5.1.3",
    "@types/recharts": "^1.1.4",
    "@types/reduce-reducers": "^0.3.0",
    "@types/storybook__react": "^4.0.0",
    "@types/styled-components": "^4.1.3",
    "@typescript-eslint/eslint-plugin": "^2.24.0",
    "ajv": "^6.6.1",
    "autoprefixer": "^9.4.2",
    "axios-mock-adapter": "^1.17.0",
    "babel-plugin-styled-components": "1.10.2",
    "boxen": "^3.0.0",
    "chalk": "^2.4.1",
    "commitizen": "^3.0.5",
    "cz-conventional-changelog": "^2.1.0",
    "docz": "^1.3.2",
    "docz-theme-default": "^1.2.0",
    "enzyme": "^3.7.0",
    "enzyme-adapter-react-16": "^1.7.0",
    "eslint": "^6.8.0",
    "eslint-config-airbnb-typescript": "^7.2.0",
    "eslint-plugin-import": "^2.20.1",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-react": "^7.19.0",
    "eslint-plugin-react-hooks": "^2.5.0",
    "execa": "^1.0.0",
    "husky": "^1.3.1",
    "hygen": "^4.0.9",
    "jest-enzyme": "^7.0.1",
    "jest-styled-components": "^6.3.1",
    "listr": "^0.14.3",
    "log-symbols": "^2.2.0",
    "mvy": "^0.1.0",
    "postcss-normalize": "^7.0.1",
    "react-app-rewire-postcss": "^3.0.2",
    "react-app-rewired": "^1.6.2",
    "react-router": "^5.1.0",
    "react-scripts": "2.1.0",
    "source-map-explorer": "^2.1.0",
    "storybook-react-router": "^1.0.2",
    "ts-jest": "^24.0.0",
    "ts-node": "8.4.0",
    "typescript": "^3.2.2",
    "xlsx": "^0.15.6"
  }
```

single-line.tsx
```
import React, { SFC, SVGProps } from "react";
import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  ResponsiveContainer,
} from "recharts";
import { connect } from "react-redux";
import { ThemeInterface, styled } from "../../theme/util/helpers";
import {
  dividerColor,
  primaryAccentBackground,
} from "../../theme/theme/colors";
import { RootState } from "../../store/root";
import { themeSelector } from "../../theme/theme.selector";

export interface LineChartProps {
  theme: ThemeInterface;
  data: {
    xAxis: string | number;
    yAxis: string | number;
  }[];
  xAxis: string;
  yAxis: string;
}

const StyledChart = styled.div``;

interface AxisTickProps extends SVGProps<SVGElement> {
  payload: {
    coordinate: number;
    index: number;
    isShow: boolean;
    offset: number;
    tickCoord: number;
    value: string;
  };
}

const CustomizedAxisTick: SFC<AxisTickProps> = (props) => {
  const { x, y, payload } = props;

  return (
    <g transform={`translate(${x}, ${y})`}>
      <text
        x={0}
        y={0}
        dy={16}
        textAnchor="end"
        fill="currentColor"
        transform="rotate(-35)"
      >
        {payload.value}
      </text>
    </g>
  );
};

const Chart: SFC<LineChartProps> = (props) => {
  const { data, xAxis, yAxis } = props;
  const dividerColour = dividerColor(props);
  const backgroundColor = primaryAccentBackground(props);

  return (
    <StyledChart>
      <ResponsiveContainer width="99%" aspect={4 / 3}>
        <LineChart
          data={data}
          width={100}
          height={100}
          margin={{
            left: 10, top: 20, right: 50, bottom: 65,
          }}
        >
          <XAxis
            stroke="currentColor"
            dataKey="xAxis"
            name={xAxis}
            tickSize={10}
            axisLine={false}
            tickMargin={10}
            tick={CustomizedAxisTick}
            minTickGap={1}
          />

          <YAxis
            stroke="currentColor"
            dataKey="yAxis"
            name={yAxis}
            tickCount={10}
            axisLine={false}
            tickLine={false}
            tickMargin={10}
          />

          <CartesianGrid
            strokeDasharray="4 4"
            stroke={dividerColour}
            vertical={false}
          />

          <Line
            type="monotone"
            dataKey="yAxis"
            stroke={dividerColour}
            name={yAxis}
            strokeWidth={2}
            dot={{
              stroke: dividerColour,
              strokeWidth: 2,
              fill: backgroundColor,
              r: 3,
            }}
            isAnimationActive={false}
          />
        </LineChart>
      </ResponsiveContainer>
    </StyledChart>
  );
};

const mapStateToProps = (state: RootState) => ({
  theme: themeSelector(state),
});

export const SingleLineChart = connect(mapStateToProps)(Chart);

export { SingleLineChart as default };
```

**Comment by colinmcparland** [comment]
Resolved: turns out I had an old eslint version installed globally 😳

**Comment by zfael** [comment]
having the same issue as you guys using the last version of eslint-config-airbnb-typescript!
downgrading it to 6.2.3 seems to fix the issue.

// package.json
```
{
  "scripts": {
    "test:lint": "eslint --ext .ts src/"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "2.26.0",
    "@typescript-eslint/parser": "2.26.0",
    "eslint": "6.6.0",
    "eslint-config-airbnb-typescript": "6.3.2",
    "eslint-plugin-import": "2.20.2"
  }
}
```

// eslint
```
module.exports = {
    parser: '@typescript-eslint/parser',
    extends: [
      'airbnb-typescript/base'
    ],
    plugins: ['import'],
    env: {
      node: true,
    },
    parserOptions: {
      project: './tsconfig.json'
    }
  };
 ```

// tsconfig.json
```
{
  "compilerOptions": {
    "target": "ES2020",
    "module": "commonjs",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "allowJs": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "esModuleInterop": true,
    "sourceMap": true,
    "outDir": "dist",
    "allowSyntheticDefaultImports": true,
    "removeComments": true,
    "preserveConstEnums": true,
    "baseUrl": ".",
    "lib": ["ES2020", "dom"],
    "typeRoots": ["src/types", "node_modules/@types"]
  },
  "include": ["src/**/*.ts"],
  "exclude": ["node_modules/**/*.ts"]
}
```
