### ISSUE TITLE
Configuration doesn't work

### ISSUE THREAD

**Issue by iwis** [iamturns/eslint-config-airbnb-typescript#93]
I installed https://github.com/typescript-eslint/typescript-eslint/ then performed steps from https://www.npmjs.com/package/eslint-config-airbnb-typescript (without React). I got the following errors:

```


C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components>npm install --save-dev eslint-config-airbnb-typescript eslint-plugin-import@^2.20.1 @typescript-eslint/eslint-plugin@^2.24.0
npm WARN eslint-plugin-import@2.20.1 requires a peer of eslint@2.x - 6.x but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/eslint-plugin@2.24.0 requires a peer of eslint@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/experimental-utils@2.24.0 requires a peer of eslint@* but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@18.1.0 requires a peer of eslint@^5.16.0 || ^6.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@18.1.0 requires a peer of eslint-plugin-jsx-a11y@^6.2.3 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@18.1.0 requires a peer of eslint-plugin-react@^7.19.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb@18.1.0 requires a peer of eslint-plugin-react-hooks@^2.5.0 || ^1.7.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-airbnb-base@14.1.0 requires a peer of eslint@^5.16.0 || ^6.8.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/parser@2.34.0 requires a peer of eslint@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/experimental-utils@2.34.0 requires a peer of eslint@* but none is installed. You must install peer dependencies yourself.
npm WARN iw-components@1.0.0 No repository field.

+ eslint-plugin-import@2.20.1
+ eslint-config-airbnb-typescript@7.2.1
+ @typescript-eslint/eslint-plugin@2.24.0
added 68 packages from 40 contributors, removed 106 packages, updated 35 packages and audited 103 packages in 19.366s
found 0 vulnerabilities


C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components>yarn eslint . --ext .ts
yarn run v1.22.4
error Command "eslint" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components>eslint . --ext .ts     
'eslint' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components>npx eslint --ext .ts .    
npx: installed 136 in 8.026s

Oops! Something went wrong! :(

ESLint: 7.0.0

Error: Failed to load parser '@typescript-eslint/parser' declared in '.eslintrc.js': Cannot find module 'eslint'
Require stack:
- C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components\node_modules\@typescript-eslint\parser\node_modules\@typescript-eslint\experimental-utils\dist\ts-eslint\Linter.js
- C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components\node_modules\@typescript-eslint\parser\node_modules\@typescript-eslint\experimental-utils\dist\ts-eslint\index.js
- C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components\node_modules\@typescript-eslint\parser\node_modules\@typescript-eslint\experimental-utils\dist\eslint-utils\RuleTester.js
- C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components\node_modules\@typescript-eslint\parser\node_modules\@typescript-eslint\experimental-utils\dist\eslint-utils\index.js
- C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components\node_modules\@typescript-eslint\parser\node_modules\@typescript-eslint\experimental-utils\dist\index.js
- C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components\node_modules\@typescript-eslint\parser\dist\analyze-scope.js
- C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components\node_modules\@typescript-eslint\parser\dist\parser.js
- C:\Users\Darek\AppData\Roaming\npm-cache\_npx\11560\node_modules\eslint\lib\cli-engine\config-array-factory.js
- C:\Users\Darek\AppData\Roaming\npm-cache\_npx\11560\node_modules\eslint\lib\cli-engine\cascading-config-array-factory.js
- C:\Users\Darek\AppData\Roaming\npm-cache\_npx\11560\node_modules\eslint\lib\cli-engine\cli-engine.js
- C:\Users\Darek\AppData\Roaming\npm-cache\_npx\11560\node_modules\eslint\lib\eslint\eslint.js
- C:\Users\Darek\AppData\Roaming\npm-cache\_npx\11560\node_modules\eslint\lib\eslint\index.js
- C:\Users\Darek\AppData\Roaming\npm-cache\_npx\11560\node_modules\eslint\lib\cli.js
- C:\Users\Darek\AppData\Roaming\npm-cache\_npx\11560\node_modules\eslint\bin\eslint.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (C:\Users\Darek\AppData\Roaming\npm-cache\_npx\11560\node_modules\eslint\node_modules\v8-compile-cache\v8-compile-cache.js:161:20)
    at Object.<anonymous> (C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components\node_modules\@typescript-eslint\parser\node_modules\@typescript-eslint\experimental-utils\dist\ts-eslint\Linter.js:4:18)
    at Module._compile (C:\Users\Darek\AppData\Roaming\npm-cache\_npx\11560\node_modules\eslint\node_modules\v8-compile-cache\v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)

C:\Users\Darek\Documents\Inne\Notatki\1.Programowanie\2.6.JavaScript\Browser\iw-components>
```

**Comment by iwis** [comment]
I also added issue here: https://github.com/typescript-eslint/typescript-eslint/issues/2049

**Comment by iamturns** [comment]
I think it's the newly released ESLint version 7 causing problems here.

Here's an issue tracking ESLint version 7 support: https://github.com/airbnb/javascript/issues/2223

In the meantime, continue to use ESLint version 6

**Comment by iwis** [comment]
Yes using ESLint 6 helped: https://stackoverflow.com/questions/61963749/how-to-use-eslint-typescript-airbnb-configuration/61965129
Thank you!
